package org.example.trainingservice.enums;

public enum TrainingCat {
    SYSTEME_MANAGEMENT_DE_LA_QUALITE,
    SANTE_ET_SECURITE_DU_TRAVAIL,
    MANAGEMENT_ENVIRONNEMENTAL,
    HYGIENE_SECURITE_ALIMENTAIRE,
    TECHNIQUE_ET_INDUSTRIEL,
    ADMINISTRATION_DES_ENTREPRISES
}
