#spring:
#  mail:
#    host: smtp.gmail.com
#    username: iambabaprince@gmail.com
#    password: xeriqttkibczpwdw
#    port: 587
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#          auth: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      clientService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
